# Book settings

title: USGS Data download
author: The CWS Lab - Auburn University
logo: cwsnew.png

# Force re-execution of notebooks on each build.
execute:
  execute_notebooks: off

# Information about where the book exists on the web
repository:
  url: https://github.com/cwslab/usgs_data   # Online location of your book
  
# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true
