# Use the official Python image
FROM mcr.microsoft.com/devcontainers/python:3.10

# Install the tools directly (No need to copy environment.yml)
RUN pip install --no-cache-dir \
    pandas \
    numpy \
    matplotlib \
    shapely \
    geopandas \
    folium \
    dataretrieval \
    jupyter \
    ipykernel

# Setup is done!
